# Schema for the configuration files of the ip_language_negotiation module.

ip_language_negotiation.settings:
  type: config_object
  label: 'IP Language Negotiation settings'
  mapping:
    ip_language_negotiation_countries:
      type: sequence
      label: 'Stores the language for each country'
      sequence:
        type: string
        label: 'Language per country'
